package com.chatRoom.constant;

/**
 * @Author Jinquan_Ou
 * @Description
 * @Date 2023-05-30 16:20
 * @Version 1.0.0
 **/
public enum MessageType {
    LOGIN, REGISTER, MESSAGE_SEND, SERVER_RESULT, LOGOUT, GET_FRIEND, FRIEND_INVITE, ACK_FRIEND_INVITE, DELETE_FRIEND,
    CREATE_GROUP, JOIN_GROUP, GET_GROUP, GROUP_CHAT, GET_CODE, IS_DELETE, CHANGE_USERDATA, FRIEND_ONLINE, DELETE_GROUP,
    MULTI_MEDIA
}
